
[functions.efi-create-charge]
enabled = true
verify_jwt = true
import_map = "./functions/efi-create-charge/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/efi-create-charge/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/efi-create-charge/*.html" ]

[functions.efi-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/efi-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/efi-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/efi-webhook/*.html" ]

[functions.efi-cancel-subscription]
enabled = true
verify_jwt = true
import_map = "./functions/efi-cancel-subscription/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/efi-cancel-subscription/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/efi-cancel-subscription/*.html" ]

[functions.efi-create-subscription]
enabled = true
verify_jwt = true
import_map = "./functions/efi-create-subscription/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/efi-create-subscription/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/efi-create-subscription/*.html" ]

[functions.validate-coupon]
enabled = true
verify_jwt = true
import_map = "./functions/validate-coupon/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/validate-coupon/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/validate-coupon/*.html" ]
